# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'client-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for client-ios
  pod 'Alamofire', '4.8.1'
  pod 'SwiftyJSON', '5.0.0'

end
